# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install

  build:
    name: Build API
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn build

  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn test

  deploy:
    name: Deploy on Firebase Functions
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Deploy to Firebase
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
